name: Reliably - Operations
description: Tell ReliablyHQ about operations that have occured as part of your pipeline.
author: Reliably
branding:
  icon: check-circle
  color: red
inputs:
  service:
    description: The name of your service
    required: true
  type:
    description: The type of operation you are performing
    required: true
  outcome:
    description: The outcome of the operation
    required: true
runs:
  using: docker
  image: docker://ghcr.io/reliablyhq/cli/cli:latest
  args:
    - entity
    - create
    - operation
    - --service
    - ${{ inputs.service }}
    - --type
    - ${{ inputs.type }}
    - --outcome
    - ${{ inputs.outcome }}
